### ISSUE TITLE
Option to ignore unparsable lines?

### ISSUE THREAD

**Issue by msonnabaum** [Ironholds/webtools#1]
The first log I tried read_combined on (from varnishncsa) contained an unencoded double-quote, which doesn't parse correctly. Here's a shortened example of what it looked like:

`
198.51.100 - - [20/Mar/2015:21:20:23 +0000] "GET http://www.example/fonts/ge-iconography-webfont.eot?)%20format("eot"),%20url(/components/bra HTTP/1.1" 200 354066
`

The resulting error is:

```
Error: At [1, 6] expecting delimiter or quote but found 'e'
```

Although the double-quote should have been encoded on the client side, it got logged that way, so it'd be nice if I could still get a data frame back with everything else.

Maybe an option could be added to ignore unparsable entries and throw a warning for each one?

**Comment by Ironholds** [comment]
Hmn; so, the problem is its recognition of quotes?

**Comment by Ironholds** [comment]
So, basically the ideal behaviour, then, would be one of two things:
1. Don't recognise quotes at all. The problem there is that it can lead to mismatched columns, at which point readr screams and cries and gives up.
2. Do recognise quotes, but either eliminate lines or smush them together when this creates weird mismatches or unexpected characters.

Both of these are pretty closely tied into an upstream proposal I've got titled [dealing with horrible files](https://github.com/hadley/readr/issues/94): the idea is that in the case where the input data is grubby, creating an inconsistent number of fields, readr would provide the option to merge fields together, allowing the row to be read in. Does this sound like it'd help?

**Comment by msonnabaum** [comment]
Yeah, the problem is the quote showing up in the middle of a string that you expect to start and end with quotes. I assumed you were using something like `"([^"]*)"` to match the request part. I see now it's actually much simpler, using `read_delim(delim = " ")`, and read_delim appears to respect quoted fields that contain the delimiter.

My first thought was that it's not worth trying to parse that correctly, because a double quote isn't a valid character in a request. I'm not sure how common this actually is.

Looking at https://github.com/hadley/readr/issues/94, I'm not sure it would help. In this case, extra quotes aren't creating more fields, because they are immediately followed by a non-delimiter character. But with that in mind, maybe this is actually more of a readr issue since it seems like the option to drop/warn would be for read_delim?

**Comment by Ironholds** [comment]
I think so? That is, we're looking for similar behaviour (warn, smush together, ignore or stop, as options) for different readr-level issues.

**Comment by msonnabaum** [comment]
Opened https://github.com/hadley/readr/issues/99, closing this.
