### ISSUE TITLE
Improve split_* functionality

### ISSUE THREAD

**Issue by Ironholds** [Ironholds/webtools#10]
split_\* calls currently fail if there's a disconnect between the expected input and the actual input, in terms of field counts. We should fix this. A resolution probably looks like:
1. Migrating the string-splitting to C++ rather than handling it R-side, meaning that we can do it string by string and as vectors instead of a list of vectors. Increases readability by reducing iterators.
2. For each request/status_code and delimiter, split into N chunks. If the number of chunks produced are <N, pad. Return and then pass off into a list, somehow.

**Comment by Ironholds** [comment]
Related to this: @hadley, what would your thoughts be (as someone who does C++ a lot) of an...I dunno. Rcppsugar package? Think exportable-to-other-libraries-with-rcpp functions for common tasks (tokenising a string, extracting the chunk of a string between two distinct delimiters)

**Comment by hadley** [comment]
Have looked at stringi at all?  It might be worth asking them to export a C++ api too

**Comment by Ironholds** [comment]
Stringi I adore, but I haven't looked at the internal workings. I'll give them a poke: thanks for the pointer!
