### ISSUE TITLE
Consider renaming this package to logreadr

### ISSUE THREAD

**Issue by ctbrown** [Ironholds/webtools#14]
The name "webreadr" is misleading.  What this package does is read log files, thus I suggest calling it **logreadr** to better reflect the function and scope of the package.  **webreadr** implies it is reading connections from the web.

**Comment by Ironholds** [comment]
Where's the place it's getting misleading? It's reading web access logs; logreadr make it sound like it reads, say, error logs.

**Comment by ctbrown** [comment]
webreadr makes it sounds like it is reading a web connection.  IMHO, the
'log' part is more important than the 'web' part. The _readr_ packages has
named the function read_log and not read_web, after all.

**Comment by Ironholds** [comment]
That sort of doesn't answer my initial question; where was it confusing people? The GitHub description makes clear what it does, the CRAN description makes clear what it does...

**Comment by ctbrown** [comment]
The name does not make it clear.  It is misleading.

**Comment by Ironholds** [comment]
I'm not seeing a big need for a namechange here, I'm afraid, particularly now that it's already on CRAN.

I accept that people might find the name slightly off, but that's what we have DESCRIPTION entries for - to clarify. Plyr would just be "tools", taken on its own; rstream could be a generalised streaming framework, taken on its own; foreign could be an FFI. Descriptions clarify these things. "webreadr" could read web connections, sure - but then logreadr could read error logs. The DESCRIPTION makes clear it does neither.
