### ISSUE TITLE
Test failures with dev readr

### ISSUE THREAD

**Issue by hadley** [Ironholds/webtools#16]
Would you mind taking a look please?

```
checking tests ... ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  121 - 1 == 120

  testthat results ================================================================
  OK: 12 SKIPPED: 0 FAILED: 6
  1. Failure (at test_readers.R#6): Common Log Format files can be read, and split_clf can split the requests 
  2. Failure (at test_readers.R#10): Common Log Format files can be read, and split_clf can split the requests 
  3. Failure (at test_readers.R#16): Combined Log Format files can be read, and split_clf can split the requests 
  4. Failure (at test_readers.R#20): Combined Log Format files can be read, and split_clf can split the requests 
  5. Failure (at test_readers.R#27): Combined Log Format files can be read 
  6. Failure (at test_readers.R#31): Combined Log Format files can be read 

  Error: testthat unit tests failed
  Execution halted
```

**Comment by Ironholds** [comment]
Shall do! (testing before the next CRAN release?)

**Comment by hadley** [comment]
Yup. When do you think you'll have time to look at this? Ideally I'd like to submit readr by the end of this week.

**Comment by Ironholds** [comment]
I'm in the middle of my big gallivanting around but realistically this evening EST or tomorrow morning EST (whenever I'm done with flying to Florida)

**Comment by hadley** [comment]
I discover some windows bugs that are going to be painful to debug, and I'm probably not going to have much time to do it the rest of this week. So no hurry, but Friday/early next week would be great

**Comment by Ironholds** [comment]
Totally!

**Comment by Ironholds** [comment]
@hadley so having dug into this it looks like the default behaviour for the log tokeniser has changed - namely it's no longer splitting on spaces (albeit with consideration of quotes and square braces). If this is an unintended consequence: upstream bug. If it's an unintended consequence you want to keep, because it's a consequence of improvements to other functionality, I'll patch around.

**Comment by hadley** [comment]
Weird. Definitely unintended because I didn't think I'd touched the log tokeniser. Could you create a minimal represent? I'll fix and add a unit test.

**Comment by Ironholds** [comment]
Totally! I'll open a bug.

**Comment by Ironholds** [comment]
With the upstream fix, webreadr's tests run perfectly! Awesome :D
