### ISSUE TITLE
Deprecate splitters?

### ISSUE THREAD

**Issue by Ironholds** [Ironholds/webtools#19]
Would appreciate @hadley 's thoughts on this (also @hrbrmstr since he's a current and future user): do we need the splitters? They're delicate as sin, increase the build time and aren't uniformly available.

At the moment I'm verging between:
1. Deprecate them
2. Totally rework them to be object-oriented and lovely and actually include NAs for missing values and then pray nobody finds a bug.

**Comment by hadley** [comment]
Can you give me a bit more context?

**Comment by hrbrmstr** [comment]
I suggest number 2! :-) We could also make it a `webreader.helpers` package (or something like that) if the build time really is bad (I didn't think so but I run high end systems). 

But, the CLF splitter would be mandatory inclusion, no? I mean, the folks who are doing weblog analysis (non-cyber) prbly want the path at least and there's no way to get that without minimal splitting.

**Comment by Ironholds** [comment]
Point! Yeah, the context is just that the implementation is eh and I wanted to work out if I should (a) improve the implementation or (b) drop it. Sounds like a :)
