### ISSUE TITLE
Provide read_aws

### ISSUE THREAD

**Issue by Ironholds** [Ironholds/webtools#2]
As [requested by Hadley](https://twitter.com/hadleywickham/status/579661349447323648)

**Comment by Ironholds** [comment]
To-do: pester Hadley for an example dataset I can test against.

**Comment by Ironholds** [comment]
@Hadley: okay, read_aws is in, and it indeed detects what fields your file has and expands or reduces the collectors and field names to match! I've tested it against your example file and the (webtools-included) AWS example; mind giving it a spin with bigger datasets/more datasets and seeing if anything chokes?

**Comment by hadley** [comment]
I wonder if we need a custom tokenizer for these files - having something that handled `[]` quoting would be nice

**Comment by Ironholds** [comment]
Is that a webtools or readr question? I assume readr?

Custom tokenisers would be nice; happy to provide feedback or thoughts from my end, but I suspect you know a lot more than me about what'd work best here ;p.

**Comment by hadley** [comment]
Just pushed a draft tokenizer - please let me know if you find log files that break it

**Comment by Ironholds** [comment]
Shall do!
