### ISSUE TITLE
read_aws : Extra fields for https

### ISSUE THREAD

**Issue by brendan-r** [Ironholds/webtools#20]
Hello,

Firstly, thanks so much for this package!

I recently setup cloudfront with a [Let's Encrypt](https://letsencrypt.org) cert, for an S3 website. Running `read_aws` on the logs fails with 

```
Error in aws_header_select(header_fields) : 
  Your file contains unrecognised fields
```

This appears to be because I have four columns which `aws_header_select` does not expect (`x-forwarded-for, ssl-protocol, ssl-cipher, x-edge-response-result-type`).

A fix for this looks simple. I'm happy to submit a PR with:
- The new fields, names, and collectors added to `aws_headers` in `R/utilities.R`
- An update to the test data (adding these columns)
- An update to the relevant [test](https://github.com/Ironholds/webreadr/blob/master/tests/testthat/test_readers.R#L36)

As `aws_header_select` doesn't require that all the column names are present, adding these fields shouldn't disturb function on http aws logs.

As you're a bit ambivalent about open-source R development at the moment, I wanted to ask, is a PR useful? Is the change likely to make its way to CRAN any time soon? What's the best/most-helpful thing for me to do?

Brendan

**Comment by Ironholds** [comment]
"a bit ambivalent" doesn't really cover it ;p. In sequence: yes, totally, this! This is a bugfix and I'm shipping bugfixes up whenever.

**Comment by brendan-r** [comment]
:+1:
