### ISSUE TITLE
Integrate IIS/Exchange CAS logs

### ISSUE THREAD

**Issue by almartin82** [Ironholds/webtools#23]

**Comment by Ironholds** [comment]
Hey @almartin82 ! Thanks for opening this bug - I've seen you've patched it on your side. Wanna pull request it in?

**Comment by Ironholds** [comment]
Wait you did and I just didn't see it; doh!

**Comment by Ironholds** [comment]
@almartin82 did you test this on your local? That is, running the unit tests? I have spotted (and fixed) 2 bugs in the code that each individually would've prevented it from working.
