### ISSUE TITLE
Provide inet_pton and equivalent

### ISSUE THREAD

**Issue by Ironholds** [Ironholds/webtools#3]
What it says on the tin. C(++) must have builtins for this; let's surface them in a vectorised way.

**Comment by Ironholds** [comment]
Having looked into the Windows equivalent of inet_pton and the restrictions around it (sorry, Windows XP users!):

[aah](http://media.giphy.com/media/zXeX29w6jxjAk/giphy.gif)

I'm gonna roll my own.

**Comment by Ironholds** [comment]
@hadley an update!

So: we now have ip_to_numeric(), which converts IP addresses to their numeric representations. It is:
1. Vectorised;
2. C++-based;
3. Capable of handling invalid IPs, so there's no real need to do sanitisation beforehand.

I've benchmarked it against the R/matrix-based function you'd put together, [here](https://gist.github.com/Ironholds/fcd181f2631dee50c83e); the TL;DR is that it's 4x as fast for short vectors, slightly-slower-but-with-a-tighter-grouping for medium-sized vectors, and 2x faster for long (>=1m element) vectors of IP addresses.

Given that mid-sized vectors can still be handled in 10ms, and I mostly expect people to be throwing millions upon millions of IPs in at a time, I'm going to declare victory.

It's in the development version; take it for a spin, see if it works for you?

**Comment by hadley** [comment]
Nice - thanks!
