### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by hadley** [Ironholds/webtools#4]
The request field contains the literal request sent to the server - there's no guarantee that it's well formed so can be parsed into method, url and version. For example, here's a request in a log file I'm processing:

"tajlvdmgtornhhkykkvynluzfmxjrnuyhifbhduwwypgvtalcpkxvjlionksmoqnjrdyrqsbkkwmjwliytplxnhkrckteshcwucxqswdulfwlckgvcqglkzbdvbtiqthqazjiaujarnwkoakagokmwcigckehdfcfvmzzuielerbrywyqczvkbtnkmudhjocyyhiplxtitddimcnebduofdpupgqrehybqfeyoywvlnqozuyylawnhznyurccgdwlgjzrduwzjoclfawjryyjzusaxygdccbqpvrgognwgpcuofbyotyfinxjhdcvadutvlpgowssjgxpmznvauwmkwwedtuerxcgstbpvhyhxrterpdokwdxnrpgcoabqszcbqisyiwplaeheqgrsbpcyiaieftbopfhpcduncfzujygvlhmismvnawjhsqgevbtuzwuvwsagcabgnfolsbzsqfepemzrobbvnzozfibdlufufbkrmwrpcavezwoifrmkhinbcnkufcukqfjxbgkdyyuopqjdvpcbundyjssjbtdgrenpcnjdyoajaaghvmvnspfgwxrrvirgiwczlvgoolbundabhmuaxyczsvbvuujpdcctyvmytzocqkzsyxotqtvebbyasmmwyjcoieholitrrilsikhgyqybarlhckxpowbsrtolkcydzqsrzvkzerpbfimkpplrszomtbifoviorrdyuhuixpdcqpkhrduwirmmvalmtpahtqybkzawhygpareegekcolikvldpjynamqjhpwejvfjewwnxnrlcxntmirrusjqngfybcqqwaanzulttqfyvjfxpummgyregzkdzusgnlizgquoinygxkqnpmfdrylwldczqitcwqahyvztllcipjuerkafnewubuoxqjqltpgtnlwlwlyxtcsaxtnwccuucnkhimquokrccdepbzmyqgebmpidbngktvlpahhtxckcshsyssexhigrrsdwtqhikqmzsyxskewqeveqlmzpxjabcubwfqtepizjnxgnsakqzudihfsibcbslyehxehcuqujwdqivg"

(this may be a buffer overrun attack?)

The split functions need some way to deal with this, or a note stating they should only be used for successful requests.

**Comment by Ironholds** [comment]
Makes sense!

**Comment by Ironholds** [comment]
Documentation improved with a note, so this is (strictly-speaking) resolved - but it should do better than this. I'm going to mark this as "done" but open up a new bug to dump all my thoughts about resolutions into (which honestly I'll probably get to, like...later today.)
