### ISSUE TITLE
Reverse ip lookup

### ISSUE THREAD

**Issue by hadley** [Ironholds/webtools#6]
Going from ip to domain names seems useful

**Comment by Ironholds** [comment]
So some sort of traceroute-like behaviour?

**Comment by hadley** [comment]
Just the equivalent of `host`

**Comment by Ironholds** [comment]
Gotcha; just a mapping to Nbtstat or nmblookup depending on platform?

**Comment by hadley** [comment]
Yeah, exactly

**Comment by Ironholds** [comment]
Cool! Makes sense :)

**Comment by Ironholds** [comment]
Now available as part of iptools!
