### ISSUE TITLE
Parse query string

### ISSUE THREAD

**Issue by hadley** [Ironholds/webtools#8]
It might be useful to have something more robust than:

```
tidyr::extract(url, c("version", "os"), "/links/\\?version=([^&]+)&os=([^&]+)")
```

to extract named query params from a url. I'm imagining something like `extract_query(url, c("version", "os")` that would return a 2-col data frame

**Comment by Ironholds** [comment]
urltools actually already does that, albeit not in a df-y way (it's one param=value pair at a time). Worth including a pointer, including in webtools with modifications, or leaving alone, y'think?

**Comment by hadley** [comment]
A df-y approach in urltools would be great

**Comment by Ironholds** [comment]
:+1:

**Comment by Ironholds** [comment]
That reminds me, I need to put out my bounty for "BDR says there's an unterminated string somewhere in urltools, valgrind disagrees, can anyone replicate so I can get this on to CRAN already?" We need a bounty board.

**Comment by Ironholds** [comment]
Now done in a dataframey way in urltools! See url_parameters()
